server:
  port: 8001
  servlet:
    context-path: /member

spring:
  application:
    name: batch
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    top.kjwang.train.member.mapper: trace