POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDExNTA2NDcsIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE3MjY1NjAxNzIwNjg5NjY0MDAsImV4cCI6MTcwMTIzNzA0NywiaWF0IjoxNzAxMTUwNjQ3fQ._jU23FtYytFGO3S2Beul7FzIKlN_bKaFWg0POW-RrPg

{
  "dailyTrainTicketId": 1729392892692271104,
  "date": 1701273600000,
  "end": "徐州站",
  "start": "上海站",
  "tickets": [
    {
      "passengerId": 1726962790993891328,
      "passengerIdCard": "887766",
      "passengerName": "煤球球",
      "passengerType": "2",
      "seatTypeCode": "1"
    }
  ],
  "trainCode": "G1"
}