POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "rose",
  "idCard": "334455",
  "type": "1"
}

###
GET http://localhost:8001/member/passenger/query-list
Accept: application/json
token: {{token}}